clear all
clc
tic
a=60;
b=40;
disp('sin(a+b)=sin(a)cos(b)+cos(a)sin(b)');
LHS=sin(a+b);
disp(LHS)
RHS=sin(a)*cos(b)+cos(a)*sin(b);
disp(RHS);
disp('sin(a-b)=sin(a)cos(b)-cos(a)sin(b)');
LHS=sin(a-b);
disp(LHS)
RHS=sin(a)*cos(b)-cos(a)*sin(b);
disp(RHS);
disp('cos(a+b)=cos(a)cos(b)-sin(a)sin(b)');
LHS=cos(a+b);
disp(LHS);
RHS=cos(a)*cos(b)-sin(a)*sin(b);
disp(RHS)
disp('tan(a+b)=tan(a)+tan(b)/1-tan(a)tan(b)');
LHS=tan(a+b);
disp(LHS);
RHS=tan(a)+tan(b)/(1-tan(a)*tan(b));
disp(RHS);
disp('tan(a-b)=tan(a)-tan(b)/1+tan(a)tan(b)');
LHS=tan(a-b);
disp(LHS);
RHS=tan(a)-tan(b)/(1+tan(a)*tan(b));
disp(RHS);
toc